Repository woowacourse-teams/2025-PhotoGather, pull requests merged in 2025-08, with the labels that each got.

#217 fix: iOS에서 백스페이스를 2번 눌러야 input에 입력된 값이 삭제되는 문제 해결
  frontend/__test__/useInputLength.test.tsx
  frontend/src/components/@common/input/Input.tsx
  frontend/src/hooks/@common/useInputLength.ts
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
Labels: FE

#226 feature: 타이머 훅 제작
  frontend/src/components/leftTimeInformationBox/LeftTimeInformationBox.tsx
  frontend/src/constants/debugMessages.ts
  frontend/src/hooks/@common/useTimer.ts
  frontend/src/stories/LeftTimeInformationBox.stories.tsx
  frontend/src/types/timer.type.ts
  frontend/src/utils/formatDate.ts
  frontend/src/utils/formatTime.ts
  frontend/src/utils/formatTimer.ts
  frontend/src/utils/isParsableToDate.ts
Labels: FE

#237 refactor: input에서 maxLength 입력 제한 삭제
  frontend/__test__/useInputLength.test.tsx
  frontend/src/components/@common/input/Input.tsx
  frontend/src/hooks/@common/useInputLength.ts
  frontend/src/stories/Input.stories.tsx
Labels: FE

#236 design: Overlay 스타일 작성
  frontend/src/styles/@common/Overlay.styles.ts
  frontend/src/styles/theme.ts
Labels: FE

#241 fix: develop이 실행되지 않는 오류 해결
  frontend/src/hooks/@common/useFileUpload.ts
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
Labels: FE

#216 feature: 로깅 추가
  backend/forgather/src/main/java/com/forgather/domain/space/controller/PhotoController.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/AwsS3Cloud.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
  backend/forgather/src/main/java/com/forgather/global/config/WebConfig.java
  backend/forgather/src/main/java/com/forgather/global/logging/LogFormatter.java
  backend/forgather/src/main/java/com/forgather/global/logging/Logger.java
  backend/forgather/src/main/java/com/forgather/global/logging/LoggingAspect.java
  backend/forgather/src/main/java/com/forgather/global/logging/TraceIdInterceptor.java
Labels: BE

#214 feature: 네트워크 에러 페이지
  frontend/__test__/isNetworkError.test.ts
  frontend/__test__/useApiCall.test.ts
  frontend/src/@assets/images/wifi.png
  frontend/src/apis/http.ts
  frontend/src/components/layout/MessageLayout/MessageLayout.styles.ts
  frontend/src/components/layout/MessageLayout/MessageLayout.tsx
  frontend/src/constants/errors.ts
  frontend/src/constants/messages.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/@common/useApiCall.ts
  frontend/src/hooks/@common/useFileUpload.ts
  frontend/src/hooks/useDownload.ts
  frontend/src/hooks/usePhotosBySpaceCode.ts
  frontend/src/pages/complete/DownloadCompletePage.tsx
  frontend/src/pages/complete/SpaceCreatedCompletePage.tsx
  frontend/src/pages/complete/UploadCompletePage.tsx
  frontend/src/pages/error/NetworkErrorPage.tsx
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/router/router.tsx
  frontend/src/utils/isNetworkError.ts
  frontend/src/utils/tryAsync.ts
Labels: FE

#242 feature: 사진 삭제 기능
  backend/forgather/src/main/java/com/forgather/domain/space/controller/PhotoController.java
  backend/forgather/src/main/java/com/forgather/domain/space/repository/PhotoRepository.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/AwsS3Cloud.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
Labels: BE

#252 feature: 안내 토스트 구현
  frontend/src/@assets/icons/info.svg
  frontend/src/App.tsx
  frontend/src/components/@common/infoBox/InfoBox.styles.ts
  frontend/src/components/@common/notification/toast/Toast.styles.ts
  frontend/src/components/@common/notification/toast/Toast.tsx
  frontend/src/components/@common/notification/toastList/ToastList.styles.ts
  frontend/src/components/@common/notification/toastList/ToastList.tsx
  frontend/src/contexts/ToastContext.tsx
  frontend/src/hooks/@common/useFileUpload.ts
  frontend/src/hooks/@common/useToast.ts
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/stories/Toast.stories.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/toast.type.ts
Labels: FE

#264 feature: 업로드시 사진 삭제 구현
  frontend/src/hooks/@common/useFileUpload.ts
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/types/file.type.ts
Labels: FE

#251 feature: 스페이스 생성 퍼널
  frontend/__test__/SpaceCreateFunnel.test.tsx
  frontend/__test__/calculateKSTDate.test.ts
  frontend/__test__/checkIsPastDateTime.test.ts
  frontend/__test__/delay.test.ts
  frontend/__test__/parseIsoStringFromDateTime.test.ts
  frontend/fileMock.ts
  frontend/jest.config.js
  frontend/jest.setup.js
  frontend/public/index.html
  frontend/src/@assets/fonts/Roboto-Mono-regular.woff2
  frontend/src/@assets/images/diamond.png
  frontend/src/apis/services/space.service.ts
  frontend/src/components/@common/highlightText/HighlightText.tsx
  frontend/src/components/@common/inputs/DateTimeInput.tsx
  frontend/src/components/@common/inputs/Input.styles.ts
  frontend/src/components/@common/inputs/textInput/TextInput.styles.ts
  frontend/src/components/@common/inputs/textInput/TextInput.tsx
  frontend/src/components/leftTimeInformationBox/LeftTimeInformationBox.styles.ts
  frontend/src/components/leftTimeInformationBox/LeftTimeInformationBox.tsx
  frontend/src/constants/messages.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/useCreateSpace.ts
  frontend/src/hooks/useFunnelHistory.ts
  frontend/src/pages/create/funnel/FunnelBasePage/FunnelBasePage.styles.ts
  frontend/src/pages/create/funnel/FunnelBasePage/FunnelBasePage.tsx
  frontend/src/pages/create/funnel/SpaceCreateFunnel.styles.ts
  frontend/src/pages/create/funnel/SpaceCreateFunnel.tsx
  frontend/src/pages/create/funnelElements/CheckSpaceInfoElement.tsx
  frontend/src/pages/create/funnelElements/DateInputElement.tsx
  frontend/src/pages/create/funnelElements/FetchElement.tsx
  frontend/src/pages/create/funnelElements/NameInputElement.tsx
  frontend/src/pages/create/funnelElements/TimeInputElement.tsx
  frontend/src/pages/create/funnelElements/waitPage/WaitPage.styles.ts
  frontend/src/pages/create/funnelElements/waitPage/WaitPage.tsx
  frontend/src/pages/demo/DemoHome.tsx
  frontend/src/pages/guest/sharePage/SharePage.styles.ts
  frontend/src/pages/guest/sharePage/SharePage.tsx
  frontend/src/router/router.tsx
  frontend/src/stories/DateInput.stories.tsx
  frontend/src/stories/TextInput.stories.tsx
  frontend/src/stories/TimeInput.stories.tsx
  frontend/src/styles/global.ts
  frontend/src/styles/reset.ts
  frontend/src/styles/theme.ts
  frontend/src/types/funnel.type.ts
  frontend/src/types/space.type.ts
  frontend/src/utils/calculateKSTDate.ts
  frontend/src/utils/checkIsPastDateTime.ts
  frontend/src/utils/delay.ts
  frontend/src/utils/parseIsoStringFromDateTime.ts
  frontend/tsconfig.json
Labels: FE

#258 feature: DB 기반 사진 일괄/선택 다운로드
  backend/forgather/src/main/java/com/forgather/domain/space/controller/PhotoController.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/DownloadPhotosRequest.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/AwsS3Cloud.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
Labels: BE

#256 feature: 익셉션 핸들링 및 에러 로깅
  backend/forgather/src/main/java/com/forgather/domain/space/util/MetaDataExtractor.java
  backend/forgather/src/main/java/com/forgather/global/exception/GlobalExceptionHandler.java
  backend/forgather/src/main/java/com/forgather/global/logging/LogFormatter.java
Labels: BE

#253 feature: Overlay 컴포넌트 제작 및 OverlayProvider 적용
  frontend/src/App.tsx
  frontend/src/components/@common/overlay/Overlay.tsx
  frontend/src/context/OverlayProvider.tsx
  frontend/src/styles/@common/BackDrop.styles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/modal.type.ts
Labels: FE

#271 feature: 레이아웃 배경 별 추가 및 그라디언트 조정
  frontend/src/@assets/icons/star-filled.svg
  frontend/src/@assets/icons/star-outlined.svg
  frontend/src/components/layout/Layout.styles.ts
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/layout/starField/StarField.styles.ts
  frontend/src/components/layout/starField/StarField.tsx
Labels: FE

#277 feature: 선택 삭제 연동 및 전체 선택 기능 제작
  frontend/.storybook/preview.tsx
  frontend/public/index.html
  frontend/public/sample.zip
  frontend/src/@assets/icons/check.svg
  frontend/src/apis/http.ts
  frontend/src/apis/services/photo.service.ts
  frontend/src/components/@common/buttons/button/Button.styles.ts
  frontend/src/components/@common/buttons/button/Button.tsx
  frontend/src/components/@common/sparkleLightTrail/SparkleLightTrail.styles.ts
  frontend/src/components/@common/sparkleLightTrail/SparkleLightTrail.tsx
  frontend/src/components/layout/LoadingLayout/LoadingLayout.styles.ts
  frontend/src/components/layout/LoadingLayout/LoadingLayout.tsx
  frontend/src/components/spaceHomeTopActionBar/SpaceHomeTopActionBar.styles.ts
  frontend/src/components/spaceHomeTopActionBar/SpaceHomeTopActionBar.tsx
  frontend/src/constants/constraints.ts
  frontend/src/constants/debugMessages.ts
  frontend/src/hooks/@common/useFileUpload.ts
  frontend/src/hooks/useCreateSpace.ts
  frontend/src/hooks/usePhotoSelect.ts
  frontend/src/hooks/usePhotosBySpaceCode.ts
  frontend/src/hooks/usePhotosDelete.ts
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/pages/manager/spaceHome/mockSpaceData.ts
  frontend/src/stories/LoadingLayout.stories.tsx
  frontend/src/styles/@common/BackDrop.styles.ts
  frontend/src/types/api.type.ts
  frontend/src/types/globals/client.d.ts
  frontend/src/utils/buildImageUrl.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: FE

#284 fix: 사진 선택 및 압축 다운로드 HTTP 메서드 변경
  backend/forgather/src/main/java/com/forgather/domain/space/controller/PhotoController.java
Labels: BE

#283 refactor: 퍼널 디자인 수정
  frontend/__mocks__/fileMock.ts
  frontend/__mocks__/svgMock.ts
  frontend/__test__/SpaceCreateFunnel.test.tsx
  frontend/jest.config.js
  frontend/src/components/@common/inputs/Input.styles.ts
  frontend/src/components/@common/notification/toastList/ToastList.styles.ts
  frontend/src/components/@common/notification/toastList/ToastList.tsx
  frontend/src/constants/messages.ts
  frontend/src/contexts/ToastContext.tsx
  frontend/src/hooks/useCreateSpace.ts
  frontend/src/hooks/useSpaceCodeFromPath.ts
  frontend/src/pages/create/funnelElements/DateInputElement.tsx
  frontend/src/pages/guest/sharePage/SharePage.tsx
  frontend/src/stories/Toast.stories.tsx
  frontend/src/types/toast.type.ts
Labels: FE

#294 fix: loading UI가 뜨는 위치 수정
  frontend/src/apis/http.ts
  frontend/src/components/@common/imageLayout/imageGrid/ImageGrid.common.styles.ts
  frontend/src/hooks/usePhotosDelete.ts
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.styles.ts
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/styles/@common/BackDrop.styles.ts
  frontend/src/styles/theme.ts
Labels: FE

#298 feature: 랜딩페이지 기본 레이아웃
  frontend/src/@assets/icons/google.svg
  frontend/src/@assets/icons/instagram.svg
  frontend/src/@assets/icons/kakaotalkLogo.svg
  frontend/src/@assets/icons/logo.svg
  frontend/src/@assets/icons/menu.svg
  frontend/src/@assets/icons/naver.svg
  frontend/src/components/header/landingHeader/LandingHeader.styles.ts
  frontend/src/components/header/landingHeader/LandingHeader.tsx
  frontend/src/components/header/spaceHeader/SpaceHeader.styles.ts
  frontend/src/components/header/spaceHeader/SpaceHeader.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/@common/useLandingScroll.ts
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/landing/LandingPage.styles.ts
  frontend/src/pages/landing/LandingPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/router/router.tsx
  frontend/src/stories/SpaceHeader.stories.tsx
  frontend/src/styles/theme.ts
Labels: FE

#295 feature: 사진 단건 조회 및 삭제 기능 구현
  frontend/src/App.tsx
  frontend/src/animations/glow.ts
  frontend/src/apis/services/photo.service.ts
  frontend/src/components/@common/buttons/iconLabelButton/IconLabelButton.styles.ts
  frontend/src/components/@common/imageLayout/imageElement/ImageElement.common.styles.ts
  frontend/src/components/@common/notification/toast/Toast.styles.ts
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/modal/ConfirmModal.styles.ts
  frontend/src/components/modal/ConfirmModal.tsx
  frontend/src/components/modal/PhotoModal.styles.ts
  frontend/src/components/modal/PhotoModal.tsx
  frontend/src/contexts/OverlayProvider.tsx
  frontend/src/hooks/useDownload.ts
  frontend/src/hooks/usePhotosDelete.ts
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/landing/LandingPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/stories/ConfirmModal.stories.tsx
  frontend/src/stories/IconLabelButton.stories.tsx
  frontend/src/utils/buildImageUrl.ts
Labels: FE

#297 feature: 각종 만료 페이지 및 레이아웃
  frontend/src/@assets/images/lock.png
  frontend/src/components/layout/statusLayout/StatusLayout.styles.ts
  frontend/src/components/layout/statusLayout/StatusLayout.tsx
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/pages/status/earlyPage/EarlyPage.styles.ts
  frontend/src/pages/status/earlyPage/EarlyPage.tsx
  frontend/src/pages/status/expiredPage/ExpiredPage.styles.ts
  frontend/src/pages/status/expiredPage/ExpiredPage.tsx
  frontend/src/stories/StatusLayout.stories.tsx
  frontend/src/utils/changeKSTDate.ts
  frontend/src/utils/checkIsEarlyTime.ts
Labels: FE

#306 refactor: 업로드 페이지 임시로 오픈 전 overlay 풀 수 있도록 수정
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
Labels: FE

#230 feature: 만료된 스페이스 접근에 대한 예외 처리
  backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceRequest.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/SpaceResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
  backend/forgather/src/main/java/com/forgather/domain/space/repository/SpaceRepository.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
  backend/forgather/src/main/resources/data.sql
  backend/forgather/src/main/resources/schema.sql
  backend/forgather/src/test/java/com/forgather/acceptance/PhotoAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/acceptance/SpaceAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/domain/space/model/SpaceTest.java
Labels: BE

#326 fix: floatButton의 zindex 값 수정
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/styles/theme.ts
Labels: FE

#322 fix: 삭제후 동일 사진 업로드 불가 문제 해결
  frontend/src/components/uploadBox/UploadBox.tsx
Labels: FE

#337 feature: GA 트래킹 추가
  frontend/public/index.html
  frontend/src/components/header/spaceHeader/SpaceHeader.tsx
  frontend/src/components/photoSelectionToolBar/PhotoSelectionToolBar.tsx
  frontend/src/hooks/@common/useLandingScroll.ts
  frontend/src/hooks/useGoogleAnalytics.ts
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/landing/LandingPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/utils/googleAnalytics/track.ts
Labels: FE

#324 feature: 스페이스 관리창 공유 링크 복사 기능 추가
  frontend/src/@assets/icons/clipboard.svg
  frontend/src/@assets/icons/link.svg
  frontend/src/@assets/icons/share.svg
  frontend/src/components/@common/modal/PhotoModal.styles.ts
  frontend/src/components/@common/modal/PhotoModal.tsx
  frontend/src/components/@common/modal/baseModal/BaseModal.styles.ts
  frontend/src/components/@common/modal/baseModal/BaseModal.tsx
  frontend/src/components/@common/modal/confirmModal/ConfirmModal.styles.ts
  frontend/src/components/@common/modal/confirmModal/ConfirmModal.tsx
  frontend/src/components/header/spaceHeader/SpaceHeader.styles.ts
  frontend/src/components/header/spaceHeader/SpaceHeader.tsx
  frontend/src/hooks/useCopyLink.ts
  frontend/src/hooks/usePhotosDelete.ts
  frontend/src/hooks/useSpaceCodeFromPath.ts
  frontend/src/pages/complete/SpaceCreatedCompletePage.tsx
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.styles.ts
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/stories/ConfirmModal.stories.tsx
  frontend/src/stories/SpaceHeader.stories.tsx
  frontend/src/utils/buildImageUrl.ts
  frontend/src/utils/createSpaceUrl.ts
Labels: FE

#349 refactor: 오픈 시간 이후에 생성 시 지금 당장 생성으로 대체
  frontend/__test__/checkIsPastDateTime.test.ts
  frontend/src/pages/create/funnel/SpaceCreateFunnel.tsx
  frontend/src/pages/create/funnelElements/CheckSpaceInfoElement.tsx
  frontend/src/utils/checkIsPastDateTime.ts
Labels: FE

#353 feature: 404 not found 페이지 제작 및 라우터 연결
  frontend/src/@assets/images/not-found.png
  frontend/src/components/@common/modal/PhotoModal.tsx
  frontend/src/constants/messages.ts
  frontend/src/pages/error/NotFoundErrorPage.tsx
  frontend/src/router/router.tsx
Labels: FE

#355 feature: 로딩 텍스트 UX 라이팅
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/stories/LoadingLayout.stories.tsx
Labels: FE

#344 feat: 민감한 API에 스페이스 호스트 검증 로직 추가
  backend/forgather/src/main/java/com/forgather/domain/space/controller/PhotoController.java
  backend/forgather/src/main/java/com/forgather/domain/space/controller/SpaceController.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceRequest.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/SpaceResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
  backend/forgather/src/main/java/com/forgather/domain/space/repository/HostRepository.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
  backend/forgather/src/main/java/com/forgather/global/auth/annotation/SessionHost.java
  backend/forgather/src/main/java/com/forgather/global/auth/domain/Host.java
  backend/forgather/src/main/java/com/forgather/global/auth/domain/SpaceHostMap.java
  backend/forgather/src/main/java/com/forgather/global/auth/dto/HostResponse.java
  backend/forgather/src/main/java/com/forgather/global/auth/resolver/HostIdArgumentResolver.java
  backend/forgather/src/main/java/com/forgather/global/auth/resolver/SessionHostArgumentResolver.java
  backend/forgather/src/main/java/com/forgather/global/config/WebConfig.java
  backend/forgather/src/main/resources/schema.sql
  backend/forgather/src/test/java/com/forgather/acceptance/PhotoAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/acceptance/SpaceAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/domain/space/model/SpaceTest.java
Labels: BE

#357 feature: 스페이스를 사용할 수 없는 경우 컴포넌트 대체
  frontend/src/components/@common/imageLayout/imageElement/fakeImageElement/FakeImageElement.styles.ts
  frontend/src/components/@common/imageLayout/imageElement/fakeImageElement/FakeImageElement.tsx
  frontend/src/components/@common/imageLayout/imageGrid/fakeImageGrid/FakeImageGrid.tsx
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/stories/FakeImageElement.stories.tsx
  frontend/src/stories/FakeImageGrid.stories.tsx
Labels: FE

#345 feature: error system 구축
  frontend/__test__/copyLinkToClipboard.test.ts
  frontend/__test__/isNetworkError.test.ts
  frontend/__test__/useApiCall.test.ts
  frontend/src/apis/http.ts
  frontend/src/apis/services/space.service.ts
  frontend/src/components/@common/modal/PhotoModal.tsx
  frontend/src/components/@common/notification/toast/Toast.styles.ts
  frontend/src/constants/errors.ts
  frontend/src/hooks/@common/useApiCall.ts
  frontend/src/hooks/@common/useError.ts
  frontend/src/hooks/@common/useFileUpload.ts
  frontend/src/hooks/useCreateSpace.ts
  frontend/src/hooks/useDownload.ts
  frontend/src/hooks/usePhotosBySpaceCode.ts
  frontend/src/hooks/usePhotosDelete.ts
  frontend/src/hooks/useSpaceInfo.ts
  frontend/src/pages/complete/UploadCompletePage.tsx
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/guest/sharePage/SharePage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/types/common.type.ts
  frontend/src/utils/copyLinkToClipboard.ts
  frontend/src/utils/isNetworkError.ts
  frontend/src/validators/fetch.validator.ts
  frontend/src/validators/photo.validator.ts
Labels: FE

#348 feature: 각종 도메인 검증 추가
  backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceRequest.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
  backend/forgather/src/test/java/com/forgather/domain/space/model/SpaceTest.java
  backend/forgather/src/test/java/com/forgather/domain/space/service/SpaceServiceTest.java
Labels: BE

#370 refactor: 썸네일 이미지 파싱 수정
  frontend/src/utils/buildImageUrl.ts
Labels: FE

#372 feature: 스페이스 생성 버튼 추가
  frontend/src/pages/landing/LandingPage.tsx
Labels: FE

#347 feature: 사진 삭제 시 썸네일 삭제
  backend/forgather/src/main/java/com/forgather/domain/space/repository/PhotoRepository.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/AwsS3Cloud.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
Labels: BE

#374 refactor: 버튼과 섹션 위치 수정
  frontend/src/pages/landing/LandingPage.tsx
Labels: FE

#363 feature: 사진 단일 다운로드
  backend/forgather/src/main/java/com/forgather/domain/space/controller/PhotoController.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/DownloadPhotoResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/AwsS3Cloud.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
Labels: BE

#380 feature: 로그에 바디를 실어 보내도록 수정
  frontend/src/apis/http.ts
  frontend/src/constants/errors.ts
  frontend/src/hooks/@common/useError.ts
  frontend/src/types/api.type.ts
  frontend/src/utils/sentry/sentryRequestContext.ts
Labels: FE

#383 fix: space 생성이 여러 번 되는 문제 해결
  frontend/src/@assets/loading-spinner.gif
  frontend/src/hooks/useCreateSpace.ts
  frontend/src/pages/create/funnel/FunnelBasePage/FunnelBasePage.tsx
  frontend/src/pages/create/funnel/SpaceCreateFunnel.tsx
  frontend/src/pages/create/funnelElements/CheckSpaceInfoElement.tsx
  frontend/src/pages/create/funnelElements/FetchElement.tsx
  frontend/src/types/funnel.type.ts
Labels: FE

#377 feat: 카카오 정보 접근 시 jwt 시그니처 검증
  backend/forgather/build.gradle
  backend/forgather/src/main/java/com/forgather/global/auth/client/KakaoAuthClient.java
  backend/forgather/src/main/java/com/forgather/global/auth/client/KakaoTokenDto.java
  backend/forgather/src/main/java/com/forgather/global/auth/scheduler/KakaoPublicKeyScheduler.java
  backend/forgather/src/main/java/com/forgather/global/auth/scheduler/RefreshTokenRemoveScheduler.java
  backend/forgather/src/main/java/com/forgather/global/auth/util/JwtParser.java
Labels: BE

#384 feat: 개발 및 로컬 환경에서 로그인 세션 유지
  backend/forgather/build.gradle
  backend/forgather/src/main/resources/application-dev.yml
  backend/forgather/src/main/resources/application-prod.yml
  backend/forgather/src/main/resources/application.yml
Labels: BE

#385 feature: 로깅 구조 변경 및 repository와 요청 본문에 대한 로깅 추가
  backend/forgather/deploy/deploy-dev.sh
  backend/forgather/deploy/deploy-prod.sh
  backend/forgather/src/main/java/com/forgather/global/logging/CustomRequestBodyInputStream.java
  backend/forgather/src/main/java/com/forgather/global/logging/CustomRequestBodyWrapper.java
  backend/forgather/src/main/java/com/forgather/global/logging/LoggingAspect.java
  backend/forgather/src/main/java/com/forgather/global/logging/LoggingInterceptor.java
  backend/forgather/src/main/java/com/forgather/global/logging/RequestWrappingFilter.java
  backend/forgather/src/main/resources/application-dev.yml
  backend/forgather/src/main/resources/application-prod.yml
  backend/forgather/src/main/resources/application.yml
  backend/forgather/src/main/resources/logback-spring.xml
Labels: BE

#406 refactor: 로그인 관련 추가 작업
  backend/forgather/src/main/java/com/forgather/global/auth/controller/AuthController.java
  backend/forgather/src/main/java/com/forgather/global/config/LoginProperties.java
  backend/forgather/src/main/java/com/forgather/global/exception/GlobalExceptionHandler.java
  backend/forgather/src/main/resources/application-dev.yml
  backend/forgather/src/main/resources/application-prod.yml
  backend/forgather/src/main/resources/application.yml
Labels: BE

#393 feature: presigned-url 방식으로 사진 업로드 추가 구현
  backend/forgather/src/main/java/com/forgather/domain/model/BaseTimeEntity.java
  backend/forgather/src/main/java/com/forgather/domain/space/controller/PhotoController.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/IssueSignedUrlRequest.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/IssueSignedUrlResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/PhotoResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/SaveUploadedPhotoRequest.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/SaveUploadedPhotoResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/FileExtension.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Photo.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/UploadFileName.java
  backend/forgather/src/main/java/com/forgather/domain/space/repository/SpaceContentRepository.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/AwsS3Cloud.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/ContentsStorage.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/UploadService.java
  backend/forgather/src/main/java/com/forgather/domain/space/util/FilePathGenerator.java
  backend/forgather/src/main/java/com/forgather/global/config/S3Config.java
  backend/forgather/src/main/resources/data.sql
  backend/forgather/src/main/resources/schema.sql
  backend/forgather/src/test/java/com/forgather/acceptance/AcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/acceptance/PhotoAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/domain/space/model/FileExtensionTest.java
  backend/forgather/src/test/java/com/forgather/domain/space/model/UploadFileNameTest.java
Labels: BE, DB 변경, API 명세 변경

#422 feature: 클라이언트 로컬에서 소셜 로그인 정상 동작하도록 지원
  backend/forgather/src/main/java/com/forgather/global/auth/client/KakaoAuthClient.java
  backend/forgather/src/main/java/com/forgather/global/auth/controller/AuthController.java
  backend/forgather/src/main/java/com/forgather/global/auth/dto/HostResponse.java
  backend/forgather/src/main/java/com/forgather/global/auth/dto/LoginResponse.java
  backend/forgather/src/main/java/com/forgather/global/auth/model/Host.java
  backend/forgather/src/main/java/com/forgather/global/auth/model/KakaoHost.java
  backend/forgather/src/main/java/com/forgather/global/auth/model/RefreshToken.java
  backend/forgather/src/main/java/com/forgather/global/auth/repository/KakaoHostRepository.java
  backend/forgather/src/main/java/com/forgather/global/auth/repository/RefreshTokenRepository.java
  backend/forgather/src/main/java/com/forgather/global/auth/service/AuthService.java
  backend/forgather/src/main/java/com/forgather/global/config/LoginProperties.java
Labels: BE

#429 refactor: 인증 체계 변경(session/cookie -> jwt)
  backend/forgather/build.gradle
  backend/forgather/src/main/java/com/forgather/global/auth/client/KakaoAuthClient.java
  backend/forgather/src/main/java/com/forgather/global/auth/controller/AuthController.java
  backend/forgather/src/main/java/com/forgather/global/auth/dto/LoginResponse.java
  backend/forgather/src/main/java/com/forgather/global/auth/dto/RefreshRequest.java
  backend/forgather/src/main/java/com/forgather/global/auth/resolver/HostIdArgumentResolver.java
  backend/forgather/src/main/java/com/forgather/global/auth/scheduler/RefreshTokenRemoveScheduler.java
  backend/forgather/src/main/java/com/forgather/global/auth/service/AuthService.java
  backend/forgather/src/main/java/com/forgather/global/auth/util/JwtTokenProvider.java
  backend/forgather/src/main/java/com/forgather/global/config/JwtProperties.java
  backend/forgather/src/main/java/com/forgather/global/config/LoginProperties.java
  backend/forgather/src/main/java/com/forgather/global/config/SwaggerConfig.java
  backend/forgather/src/main/resources/application-dev.yml
  backend/forgather/src/main/resources/application-prod.yml
  backend/forgather/src/main/resources/application.yml
  backend/forgather/src/main/resources/schema.sql
Labels: BE, DB 변경, API 명세 변경

#430 fix: 로그인 정보 없을 시 정상 처리되도록 수정
  backend/forgather/src/main/java/com/forgather/global/auth/resolver/HostIdArgumentResolver.java
Labels: BE

#415 feature: 스페이스 업데이트 API
  backend/forgather/build.gradle
  backend/forgather/src/main/java/com/forgather/domain/space/controller/SpaceController.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/UpdateSpaceRequest.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
  backend/forgather/src/main/java/com/forgather/global/config/ValidatorConfig.java
  backend/forgather/src/main/java/com/forgather/global/exception/GlobalExceptionHandler.java
  backend/forgather/src/test/java/com/forgather/domain/space/model/SpaceTest.java
  backend/forgather/src/test/java/com/forgather/domain/space/service/SpaceServiceTest.java
Labels: BE

#416 feature: 스페이스 삭제 API
  backend/forgather/src/main/java/com/forgather/domain/space/controller/SpaceController.java
  backend/forgather/src/main/java/com/forgather/domain/space/repository/SpaceRepository.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
Labels: BE

#438 refactor: cors 정책 설정 변경
  backend/forgather/src/main/resources/application-dev.yml
  backend/forgather/src/main/resources/application-prod.yml
  backend/forgather/src/main/resources/application.yml
Labels: BE

#413 feature: 사진 다운로드 url
  backend/forgather/src/main/java/com/forgather/domain/space/controller/PhotoController.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/DownloadUrlsResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/AwsS3Cloud.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/ContentsStorage.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
  backend/forgather/src/main/resources/schema.sql
  backend/forgather/src/test/java/com/forgather/acceptance/PhotoAcceptanceTest.java
Labels: BE

#445 feat: 스페이스 정보 조회 시 통계 정보 추가
  backend/forgather/src/main/java/com/forgather/domain/space/dto/SpaceResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
Labels: BE, API 명세 변경

#447 feature: DonutGraph 구현
  frontend/src/components/donutGraph/DonutGraph.styles.ts
  frontend/src/components/donutGraph/DonutGraph.tsx
  frontend/src/stories/DonutGraph.stories.tsx
Labels: FE

#425 feature: Web Share API 연동
  frontend/src/constants/messages.ts
  frontend/src/hooks/useDownload.ts
  frontend/src/hooks/useWebShareAPI.ts
  frontend/src/pages/create/funnelElements/CheckSpaceInfoElement.tsx
  frontend/src/pages/guest/sharePage/SharePage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHome.tsx
  frontend/src/utils/checkIsIos.ts
  frontend/src/validators/share.validator.ts
Labels: FE

#451 feature: 스페이스 대시보드 및 수정 페이지 제작
  frontend/.gitignore
  frontend/.prettierignore
  frontend/src/@assets/icons/edit.svg
  frontend/src/@assets/icons/warning.svg
  frontend/src/components/@common/modal/PhotoModal.tsx
  frontend/src/components/@common/modal/confirmModal/ConfirmModal.styles.ts
  frontend/src/components/@common/modal/confirmModal/ConfirmModal.tsx
  frontend/src/components/comingSoonBox/ComingSoonBox.styles.ts
  frontend/src/components/comingSoonBox/ComingSoonBox.tsx
  frontend/src/components/dashboardBox/DashboardBox.styles.ts
  frontend/src/components/dashboardBox/DashboardBox.tsx
  frontend/src/components/layout/statusLayout/StatusLayout.tsx
  frontend/src/constants/messages.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/usePhotosDelete.ts
  frontend/src/hooks/useSpaceCodeFromPath.ts
  frontend/src/pages/guest/sharePage/SharePage.tsx
  frontend/src/pages/manager/dashboard/DashboardPage.styles.ts
  frontend/src/pages/manager/dashboard/DashboardPage.tsx
  frontend/src/pages/manager/settings/SettingsPage.styles.ts
  frontend/src/pages/manager/settings/SettingsPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHomePage.styles.ts
  frontend/src/pages/manager/spaceHome/SpaceHomePage.tsx
  frontend/src/router/router.tsx
  frontend/src/stories/ConfirmModal.stories.tsx
  frontend/src/stories/DashboardBox.stories.tsx
  frontend/src/stories/SpaceManagerImageGrid.stories.tsx
  frontend/src/styles/@common/BackDrop.styles.ts
Labels: FE

#453 refactor: presigned url에 따른 다운로드 로직 변경
  frontend/package-lock.json
  frontend/package.json
  frontend/src/@assets/icons/edit.svg
  frontend/src/apis/services/guest.service.ts
  frontend/src/apis/services/photo.service.ts
  frontend/src/components/@common/inputs/Input.styles.ts
  frontend/src/components/@common/modal/Modal.common.styles.ts
  frontend/src/components/@common/modal/baseModal/BaseModal.styles.ts
  frontend/src/components/@common/modal/baseModal/BaseModal.tsx
  frontend/src/components/@common/modal/confirmModal/ConfirmModal.styles.ts
  frontend/src/components/@common/modal/confirmModal/ConfirmModal.tsx
  frontend/src/components/@common/modal/inputModal/InputModal.styles.ts
  frontend/src/components/@common/modal/inputModal/InputModal.tsx
  frontend/src/components/@common/modal/photoModal/PhotoModal.styles.ts
  frontend/src/components/@common/modal/photoModal/PhotoModal.tsx
  frontend/src/components/userBadge/UserBadge.styles.ts
  frontend/src/components/userBadge/UserBadge.tsx
  frontend/src/constants/errors.ts
  frontend/src/constants/nickNames.ts
  frontend/src/contexts/OverlayProvider.tsx
  frontend/src/hooks/@common/useError.ts
  frontend/src/hooks/@common/useFileUpload.ts
  frontend/src/hooks/useDownload.ts
  frontend/src/hooks/useGuestNickName.tsx
  frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
  frontend/src/pages/manager/dashboard/DashboardPage.tsx
  frontend/src/pages/manager/spaceHome/SpaceHomePage.tsx
  frontend/src/stories/ConfirmModal.stories.tsx
  frontend/src/stories/InputModal.stories.tsx
  frontend/src/stories/UserBadge.stories.tsx
  frontend/src/styles/@common/ScrollableBlurArea.ts
  frontend/src/types/guest.type.ts
  frontend/src/types/photo.type.ts
  frontend/src/utils/buildImageUrl.ts
  frontend/src/utils/createRandomNickName.ts
  frontend/src/utils/removeWhiteSpace.ts
  frontend/src/validators/fetch.validator.ts
Labels: FE

#452 feature: 마이 페이지 및 로그아웃 페이지 제작
  frontend/src/@assets/icons/defaultImage.svg
  frontend/src/@assets/icons/group.svg
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/layout/global/header/Header.styles.ts
  frontend/src/components/layout/global/header/Header.tsx
  frontend/src/components/profile/Profile.styles.ts
  frontend/src/components/profile/Profile.tsx
  frontend/src/components/spaceCard/SpaceCard.styles.ts
  frontend/src/components/spaceCard/SpaceCard.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/@common/useLeftTimer.ts
  frontend/src/pages/logout/LogoutPage.styles.ts
  frontend/src/pages/logout/LogoutPage.tsx
  frontend/src/pages/mypage/MyPage.styles.ts
  frontend/src/pages/mypage/MyPage.tsx
  frontend/src/router/router.tsx
  frontend/src/stories/Profile.stories.tsx
  frontend/src/stories/SpaceCard.stories.tsx
  frontend/src/styles/global.ts
  frontend/src/types/route.type.ts
  frontend/src/utils/calculateKstToday.ts
  frontend/src/utils/changeKSTDate.ts
  frontend/src/utils/dateTimeFormatters.ts
  frontend/src/utils/formatTimer.ts
Labels: FE

#462 feature: uploadFile에 capacityValue 필드 추가
  frontend/src/hooks/@common/useLocalFile.ts
  frontend/src/hooks/useFileUpload.ts
  frontend/src/stories/SpaceManagerImageElement.stories.tsx
  frontend/src/stories/SpaceManagerImageGrid.stories.tsx
  frontend/src/types/file.type.ts
  frontend/src/types/photo.type.ts
Labels: FE

#475 fix: 로딩이 움직이지 않는 문제 해결
  frontend/src/hooks/useDownload.ts
Labels: FE

#477 fix: 로컬스토리지에서 쿠키로 변경
  frontend/src/hooks/useGuestNickName.tsx
Labels: FE

#497 fix: 업로드 중 오류가 발생한 경우
  frontend/src/hooks/useFileUpload.ts
Labels: FE

#484 feature: enter 업로드 기능 추가 및 디자인 점검
  frontend/src/components/@common/modal/Modal.common.styles.ts
  frontend/src/components/@common/modal/inputModal/InputModal.tsx
  frontend/src/components/@common/modal/photoModal/PhotoModal.styles.ts
  frontend/src/components/layout/loadingLayout/LoadingLayout.tsx
  frontend/src/pages/manager/spaceHome/SpaceHomePage.styles.ts
  frontend/src/pages/manager/spaceHome/SpaceHomePage.tsx
  frontend/src/styles/@common/BackDrop.styles.ts
Labels: FE

#489 refactor: 퍼널 관련 QA 사항 수정
  frontend/src/constants/messages.ts
  frontend/src/hooks/domain/useImmediateOpenElement.ts
  frontend/src/hooks/useFunnelHistory.ts
  frontend/src/pages/create/funnelElements/DateInputElement.tsx
  frontend/src/pages/create/funnelElements/NameInputElement.tsx
  frontend/src/pages/create/funnelElements/TimeInputElement.tsx
  frontend/src/pages/create/funnelElements/immediateOpenElement/ImmediateOpenElement.tsx
  frontend/src/pages/guest/sharePage/SharePage.styles.ts
  frontend/src/pages/guest/sharePage/SharePage.tsx
Labels: FE

#493 fix: 헤더 분기처리 및 프로필 이미지 설정
  frontend/src/@assets/images/default_profile.png
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/layout/global/header/Header.tsx
  frontend/src/components/spaceCard/SpaceCard.tsx
  frontend/src/pages/logout/LogoutPage.tsx
  frontend/src/pages/mypage/MyPage.styles.ts
  frontend/src/pages/mypage/MyPage.tsx
  frontend/src/router/router.tsx
  frontend/src/types/route.type.ts
Labels: FE

#488 fix: emoji의 올바른 길이를 반환하도록 수정
  frontend/src/components/@common/inputs/textInput/TextInput.tsx
  frontend/src/components/@common/modal/inputModal/InputModal.tsx
  frontend/src/hooks/@common/useGraphemeInput.ts
  frontend/src/pages/create/funnelElements/NameInputElement.tsx
  frontend/src/pages/manager/settings/SettingsPage.tsx
Labels: FE

#504 feature: 링크 공유시 미리보기 썸네일 및 파비콘 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/webpack.config.js
Labels: FE

#508 feature: 마이페이지 만료일 연동 및 디자인 수정
  frontend/src/components/@common/buttons/button/Button.styles.ts
  frontend/src/components/@common/modal/Modal.common.styles.ts
  frontend/src/components/spaceCard/SpaceCard.styles.ts
  frontend/src/components/spaceCard/SpaceCard.tsx
  frontend/src/pages/mypage/MyPage.tsx
  frontend/src/stories/SpaceCard.stories.tsx
  frontend/src/styles/@common/BackDrop.styles.ts
  frontend/src/utils/dateTimeFormatters.ts
  frontend/src/utils/formatDate.ts
Labels: FE

#511 fix: 사진이 올라간 스페이스 삭제 API Cascade 문제 수정
  backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
Labels: BE

#516 refactor: 스페이스 정보 페이지의 수정 로직 변경
  frontend/src/apis/services/space.service.ts
  frontend/src/hooks/@common/useGraphemeInput.ts
  frontend/src/hooks/useSpaceInfo.ts
  frontend/src/pages/manager/settings/SettingsPage.tsx
Labels: FE

#522 feature: 대시보드 데이터 연동
  frontend/src/apis/services/space.service.ts
  frontend/src/components/dashboardBox/DashboardBox.styles.ts
  frontend/src/components/dashboardBox/DashboardBox.tsx
  frontend/src/hooks/useSpaceCapacity.ts
  frontend/src/pages/manager/dashboard/DashboardPage.styles.ts
  frontend/src/pages/manager/dashboard/DashboardPage.tsx
  frontend/src/types/space.type.ts
Labels: FE

#534 fix: 카카오 브라우저일 경우 외부 브라우저로 연결될 수 있도록 설정
  frontend/src/components/layout/Layout.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/@common/useKakaoRedirect.ts
  frontend/src/pages/create/funnel/SpaceCreateFunnel.tsx
  frontend/src/pages/error/OpenBrowser.styles.ts
  frontend/src/pages/error/OpenBrowser.tsx
  frontend/src/router/router.tsx
Labels: FE

#544 fix: 로그인한 상태에서도 공개 스페이스에 접근 가능하도록 변경
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
  backend/forgather/src/test/resources/application.yml
Labels: BE

#549 fix: 다운로드 기능 안정화를 위한 업로드 헤더 수정
  frontend/src/apis/http.ts
  frontend/src/hooks/useDownload.ts
Labels: FE

#547 fix: 퍼널 순서 정상화
  frontend/src/pages/create/funnel/SpaceCreateFunnel.tsx
Labels: FE
