Repository woowacourse-teams/2025-PhotoGather, pull requests merged in 2025-10, with the labels that each got.

#657 feature: v2에 맞게 db 및 설정 변경
  .coderabbit.yaml
  .github/workflows/backend-test.yml
  backend/forgather/src/main/java/com/forgather/global/config/SwaggerConfig.java
  backend/forgather/src/main/resources/application-dev.yml
  backend/forgather/src/main/resources/application-prod.yml
  backend/forgather/src/main/resources/data.sql
  backend/forgather/src/main/resources/db/migration/V1__create_initial_tables.sql
  backend/forgather/src/main/resources/db/migration/V2__add_agreed_terms_on_host_table.sql
  backend/forgather/src/main/resources/db/migration/V3__add_type_column_on_space_table.sql
  backend/forgather/src/main/resources/db/migration/V4__add_unique_constraint_on_space_code.sql
  backend/forgather/src/test/resources/application.yml
Labels: BE, DB 변경, V2

#658 chore: ci-cd build 과정에서 branch를 지정
  backend/forgather/deploy/buildspec-dev.yml
  backend/forgather/deploy/buildspec-prod.yml
Labels: BE, V2

#669 feat: 공통 컴포넌트 분리
  frontend/biome.json
  frontend/src/@assets/logo.svg
  frontend/src/components/@common/buttons/button/Button.styles.ts
  frontend/src/components/@common/buttons/button/Button.tsx
  frontend/src/components/@common/buttons/iconButton/IconButton.styles.ts
  frontend/src/components/@common/buttons/iconButton/IconButton.tsx
  frontend/src/components/@common/header/Header.styles.ts
  frontend/src/components/@common/header/Header.tsx
  frontend/src/components/@common/inputs/TextInput.styles.ts
  frontend/src/components/@common/inputs/TextInput.tsx
  frontend/src/components/@common/notification/toast/Toast.styles.ts
  frontend/src/components/@common/notification/toast/Toast.tsx
  frontend/src/constants/constraints.ts
  frontend/src/hooks/@common/useGraphemeInput.ts
  frontend/src/stories/Button.stories.tsx
  frontend/src/stories/Header.stories.tsx
  frontend/src/stories/IconButton.stories.tsx
  frontend/src/stories/TextInput.stories.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/button.type.ts
  frontend/src/types/header.type.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.node.json
Labels: FE, V2

#670 feature: API Client 정의
  frontend/src/apis/config.ts
  frontend/src/apis/http.ts
  frontend/src/types/api.type.ts
  frontend/src/utils/createQueryString.ts
Labels: FE, V2

#677 feature: 전시 작품 관련 API 구현
  .coderabbit.yaml
  backend/forgather/src/main/java/com/forgather/domain/product/controller/ProductController.java
  backend/forgather/src/main/java/com/forgather/domain/product/dto/ProductPhotoResponse.java
  backend/forgather/src/main/java/com/forgather/domain/product/dto/ProductResponse.java
  backend/forgather/src/main/java/com/forgather/domain/product/dto/RegisterProductPhotoRequest.java
  backend/forgather/src/main/java/com/forgather/domain/product/dto/RegisterProductRequest.java
  backend/forgather/src/main/java/com/forgather/domain/product/dto/UpdateProductRequest.java
  backend/forgather/src/main/java/com/forgather/domain/product/model/Product.java
  backend/forgather/src/main/java/com/forgather/domain/product/model/ProductPhoto.java
  backend/forgather/src/main/java/com/forgather/domain/product/model/ProductPhotos.java
  backend/forgather/src/main/java/com/forgather/domain/product/repository/ProductPhotoRepository.java
  backend/forgather/src/main/java/com/forgather/domain/product/repository/ProductRepository.java
  backend/forgather/src/main/java/com/forgather/domain/product/repository/jpa/ProductJpaRepository.java
  backend/forgather/src/main/java/com/forgather/domain/product/repository/jpa/ProductPhotoJpaRepository.java
  backend/forgather/src/main/java/com/forgather/domain/product/service/ProductService.java
  backend/forgather/src/main/java/com/forgather/domain/space/controller/SpaceController.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceRequest.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/SpaceResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Photo.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Product.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/ProductPhoto.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
  backend/forgather/src/main/java/com/forgather/domain/space/repository/SpaceRepository.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
  backend/forgather/src/main/java/com/forgather/domain/upload/AwsS3Cloud.java
  backend/forgather/src/main/java/com/forgather/domain/upload/ContentsStorage.java
  backend/forgather/src/main/java/com/forgather/domain/upload/service/UploadService.java
  backend/forgather/src/main/java/com/forgather/global/exception/BaseNullPointerException.java
  backend/forgather/src/test/java/com/forgather/acceptance/AcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/acceptance/PhotoAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/acceptance/ProductAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/domain/product/model/ProductPhotoTest.java
  backend/forgather/src/test/java/com/forgather/domain/product/model/ProductPhotosTest.java
  backend/forgather/src/test/java/com/forgather/domain/product/model/ProductTest.java
  backend/forgather/src/test/java/com/forgather/domain/space/model/SpaceTest.java
  backend/forgather/src/test/java/com/forgather/fixture/ProductFixture.java
  backend/forgather/src/test/java/com/forgather/fixture/ProductPhotoFixture.java
  backend/forgather/src/test/java/com/forgather/fixture/SpaceFixture.java
  backend/forgather/src/test/resources/cleanup.sql
Labels: BE, DB 변경, API 명세 변경, V2

#678 feature: 모달 컴포넌트 작성
  frontend/src/components/@common/modal/Modal.styles.ts
  frontend/src/components/@common/modal/Modal.tsx
  frontend/src/components/@common/overlay/Overlay.tsx
  frontend/src/components/layout/global/layout/Layout.tsx
  frontend/src/contexts/ModalContext.ts
  frontend/src/contexts/OverlayContext.ts
  frontend/src/contexts/OverlayProvider.tsx
  frontend/src/hooks/@common/useScrollLock.ts
  frontend/src/hooks/domain/modal/useEscapeKeyClose.ts
  frontend/src/hooks/useOverlay.ts
  frontend/src/stories/Modal.stories.tsx
  frontend/src/styles/@common/BackDrop.styles.ts
  frontend/src/types/modal.type.ts
  frontend/src/types/overlay.type.ts
Labels: FE, V2

#676 feature: 스페이스 정보 UI 제작
  frontend/src/animations/staggerFadeUp.ts
  frontend/src/components/@common/buttons/button/Button.styles.ts
  frontend/src/components/host/infoRow/InfoRow.styles.ts
  frontend/src/components/host/infoRow/InfoRow.tsx
  frontend/src/pages/host/Host.common.styles.ts
  frontend/src/pages/host/dashBoard/DashBoard.styles.ts
  frontend/src/pages/host/dashBoard/DashBoard.tsx
  frontend/src/pages/host/mainPage/HostMainPage.styles.ts
  frontend/src/pages/host/mainPage/HostMainPage.tsx
  frontend/src/pages/mockData.ts
  frontend/src/router/router.tsx
Labels: FE, V2

#683 chore: storybook autodocs 설정
  frontend/.storybook/main.ts
  frontend/package-lock.json
  frontend/package.json
Labels: FE, V2

#687 feature: 삭제 모달 / QR 생성 모달 제작
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/@common/buttons/button/Button.styles.ts
  frontend/src/components/@common/buttons/button/Button.tsx
  frontend/src/components/@common/buttons/iconButton/IconButton.styles.ts
  frontend/src/components/@common/buttons/iconButton/IconButton.tsx
  frontend/src/components/@common/header/Header.tsx
  frontend/src/components/@common/modal/Modal.styles.ts
  frontend/src/components/@common/modal/deleteModal/DeleteModal.styles.ts
  frontend/src/components/@common/modal/deleteModal/DeleteModal.tsx
  frontend/src/components/@common/notification/toast/Toast.styles.ts
  frontend/src/components/@common/notification/toastList/ToastList.styles.ts
  frontend/src/components/@common/notification/toastList/ToastList.tsx
  frontend/src/components/@common/qrCode/QRCode.tsx
  frontend/src/components/layout/global/layout/Layout.tsx
  frontend/src/components/specific/modal/spaceShareModal/SpaceShareModal.styles.ts
  frontend/src/components/specific/modal/spaceShareModal/SpaceShareModal.tsx
  frontend/src/hooks/@common/useImageDownload.ts
  frontend/src/pages/host/dashBoard/DashBoard.tsx
  frontend/src/pages/host/mainPage/HostMainPage.tsx
  frontend/src/stories/IconButton.stories.tsx
  frontend/src/types/button.type.ts
  frontend/src/types/toast.type.ts
  frontend/src/utils/coptLinkToClipboard.ts
  frontend/src/utils/webShareApi.ts
  frontend/src/validators/share.validators.ts
Labels: FE, V2

#696 refactor: 파일 업로드 관련 로직 리팩터링
  backend/forgather/src/main/java/com/forgather/domain/product/controller/ProductController.java
  backend/forgather/src/main/java/com/forgather/domain/product/service/ProductService.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
  backend/forgather/src/main/java/com/forgather/domain/space/util/FilePathGenerator.java
  backend/forgather/src/main/java/com/forgather/domain/space/util/MetaDataExtractor.java
  backend/forgather/src/main/java/com/forgather/domain/space/util/ZipGenerator.java
  backend/forgather/src/main/java/com/forgather/domain/upload/AwsS3Cloud.java
  backend/forgather/src/main/java/com/forgather/domain/upload/controller/UploadController.java
  backend/forgather/src/main/java/com/forgather/domain/upload/domain/ContentsStorage.java
  backend/forgather/src/main/java/com/forgather/domain/upload/domain/FilePathGenerator.java
  backend/forgather/src/main/java/com/forgather/domain/upload/domain/SignedUrlIssuer.java
  backend/forgather/src/main/java/com/forgather/domain/upload/domain/UploadCategory.java
  backend/forgather/src/main/java/com/forgather/domain/upload/domain/UploadFileName.java
  backend/forgather/src/main/java/com/forgather/domain/upload/dto/IssueSignedUrlRequest.java
  backend/forgather/src/main/java/com/forgather/domain/upload/dto/IssueSignedUrlResponse.java
  backend/forgather/src/main/java/com/forgather/domain/upload/service/UploadService.java
  backend/forgather/src/main/resources/application-dev.yml
  backend/forgather/src/main/resources/application-prod.yml
  backend/forgather/src/main/resources/application.yml
  backend/forgather/src/test/java/com/forgather/acceptance/PhotoAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/acceptance/UploadAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/domain/upload/domain/SignedUrlIssuerTest.java
  backend/forgather/src/test/java/com/forgather/domain/upload/domain/UploadFileNameTest.java
  backend/forgather/src/test/java/com/forgather/fake/FakeContentStorage.java
Labels: BE, API 명세 변경, V2

#689 feature: 마이페이지 구현
  frontend/src/components/@common/dropdown/Dropdown.styles.ts
  frontend/src/components/@common/dropdown/Dropdown.tsx
  frontend/src/components/@common/header/Header.styles.ts
  frontend/src/components/@common/thumbnail/Thumbnail.styles.ts
  frontend/src/components/@common/thumbnail/Thumbnail.tsx
  frontend/src/components/host/spaceCard/SpaceCard.styles.ts
  frontend/src/components/host/spaceCard/SpaceCard.tsx
  frontend/src/components/layout/global/layout/Layout.styles.ts
  frontend/src/hooks/domain/useSpacesDisplay.ts
  frontend/src/pages/host/mypage/MyPage.styles.ts
  frontend/src/pages/host/mypage/MyPage.tsx
  frontend/src/pages/mockData.ts
  frontend/src/router/router.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/space.type.ts
Labels: FE, V2

#698 feature: 스페이스 API
  backend/forgather/src/main/java/com/forgather/domain/space/controller/SpaceController.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceRequest.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/SpaceCapacityResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/SpacePhotoResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/SpaceResponse.java
  backend/forgather/src/main/java/com/forgather/domain/space/dto/UpdateSpaceRequest.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Photo.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
  backend/forgather/src/main/java/com/forgather/domain/space/model/SpacePhoto.java
  backend/forgather/src/main/java/com/forgather/domain/space/repository/SpacePhotoRepository.java
  backend/forgather/src/main/java/com/forgather/domain/space/repository/jpa/SpacePhotoJpaRepository.java
  backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
  backend/forgather/src/main/java/com/forgather/global/auth/model/Host.java
  backend/forgather/src/main/java/com/forgather/global/auth/model/SpaceHostMap.java
  backend/forgather/src/main/java/com/forgather/global/auth/repository/SpaceHostMapRepository.java
  backend/forgather/src/main/java/com/forgather/global/auth/repository/jpa/SpaceHostMapJpaRepository.java
  backend/forgather/src/test/java/com/forgather/acceptance/AcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/acceptance/PhotoAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/acceptance/ProductAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/acceptance/SpaceAcceptanceTest.java
  backend/forgather/src/test/java/com/forgather/domain/space/model/SpaceTest.java
  backend/forgather/src/test/java/com/forgather/domain/space/service/SpaceServiceTest.java
  backend/forgather/src/test/java/com/forgather/fixture/HostFixture.java
  backend/forgather/src/test/java/com/forgather/fixture/SpaceFixture.java
Labels: BE, API 명세 변경, V2
